### ISSUE TITLE
Fatal error: Uncaught Error: Cannot instantiate abstract class PrestaSmsController in 

### ISSUE THREAD

**Issue by simjank** [BulkGate/prestasms#9]
In prestashop 1.6.1.13, PHP  i have this error:
Fatal error: Uncaught Error: Cannot instantiate abstract class PrestaSmsController in public_html/classes/controller/Controller.php:134 
Stack trace: 
#0 public_html/classes/Dispatcher.php(359): ControllerCore::getController('PrestaSmsContro...') 
#1 /public_html/mg6gprcbknrxo4kj/index.php(58): DispatcherCore->dispatch() 
#2 {main} thrown in /public_html/classes/controller/Controller.php on line 134

**Comment by simjank** [comment]
I have fount, that this issue is only in multistore. until store is not selected. After store selection it works

**Comment by MartinKreizl** [comment]
Minimum supported version of module is PS 1.7.8.0
